name: Supernaturals2
version: 1.0.0
main: supernaturals.Supernaturals
api-version: 1.20 # The version of the Bukkit API your plugin is built against
description: A unique combat experience for NovusCraft!
author: Chucknorris1010, original plugin written by ELCHILEN0
website: https://example.com
depend: [] # Optional: Specify other plugins your plugin depends on
softdepend: [] # Optional: Specify soft dependencies (won't prevent your plugin from loading if missing)
load: STARTUP # Optional: Choose when the plugin should be loaded (STARTUP, POSTWORLD, etc.)
commands:
  supernaturals:
    aliases: [supernaturals, sn]

